### ISSUE TITLE
[bug] `cargo install ast-grep` fails

### ISSUE THREAD

**Issue by rg7663** [ast-grep/ast-grep#2525]
### Please read the FAQ for the bug you encountered.

- [x] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#n/a

### 💻 Code

N/A

### 🙁 Actual behavior

`cargo install ast-grep` fails with:

```
   ...
   Compiling ast-grep-lsp v0.41.0
error[E0063]: missing field `offset_encoding` in initializer of `tower_lsp_server::ls_types::InitializeResult`
  --> /home/dev/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ast-grep-lsp-0.41.0/src/lib.rs:86:8
   |
86 |     Ok(InitializeResult {
   |        ^^^^^^^^^^^^^^^^ missing `offset_encoding`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `ast-grep-lsp` (lib) due to 1 previous error
```

Same behaviour with `cargo install ast-grep@=0.40`, but works with `cargo install ast-grep@=0.39`.

### 🙂 Expected behavior

`cargo install ast-grep` installs 0.41 successfully.

### Additional information about the issue

Tested on Raspberry Pi running Raspbian and Arch Linux x86_64, as well as within archlinux docker containers on both, with exactly same outcomes in all cases. Recent or latest rust installs using rustup as well.

I've had a look git blame for ast-grep-lsp, tower-lsp-server, and ls-types and, as far as I can see, the problem likely arises where ast-grep has bumped the tower-lsp-server version from [0.21 to 0.23](https://github.com/tower-lsp-community/tower-lsp-server/commit/3e9a058497730c691e00a765fb44a764e1466c5f#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R29-L41) which in turn bumped ls-types from [github main branch to 0.0](https://github.com/tower-lsp-community/tower-lsp-server/commit/3e9a058497730c691e00a765fb44a764e1466c5f#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R29). However, the introduction of `offset_encoding` stems from a [5 year-old commit](https://github.com/tower-lsp-community/ls-types/commit/0df2afc78894c8b32c76697a22dc5e92a46f4ec7). So... I don't know why this is only appearing now.

What's strange, at least for me, is that ast-grep 0.41 compiled and installed successfully for me recently, i.e. within the last month or so, so I don't know why this is happening to me now.

**Comment by HerringtonDarkholme** [comment]
Thanks for the report.

**Comment by HerringtonDarkholme** [comment]
The issue comes from ls-types, where it is previously 0.0.2, now it is 0.0.6

ver 0.0.2

<img width="530" height="289" alt="Image" src="https://github.com/user-attachments/assets/20cac4c0-5a85-4141-9781-26cceaf6c468" />

ver 0.0.6
<img width="1064" height="452" alt="Image" src="https://github.com/user-attachments/assets/f822292c-9dea-4b43-ba95-8609d24f55d0" />

Basically, ls-types shipped a breaking change and tower-lsp-server is not locking the version

**Comment by mrnossiom** [comment]
As the maintainer of both `tower-lsp-server` and `ls-types`, I am sorry about that. 

The v0.1 `ls-types` version is around the corner and a new `tower-lsp-server` version will follow.

In the meantime and as general information, to get a reproducible build using the lockfile of `ast-grep` or whatever crate you are installing, you can use the [`--locked` flag](https://doc.rust-lang.org/cargo/commands/cargo-install.html#option-cargo-install---locked) on `cargo install`.
